// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SljemeTimeAttack.Data;

#nullable disable

namespace SljemeTimeAttack.Migrations
{
    [DbContext(typeof(SljemeTimeAttackDbContext))]
    [Migration("20260531105828_Lab5IdentityRunFiles")]
    partial class Lab5IdentityRunFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedDriverId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedDriverId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuspensionId")
                        .HasColumnType("int");

                    b.Property<int>("TireId")
                        .HasColumnType("int");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("SuspensionId");

                    b.HasIndex("TireId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Horsepower = 231,
                            Make = "Mazda",
                            Model = "RX-8 2004.",
                            RegistrationNumber = "ZG1234AA",
                            SuspensionId = 1,
                            TireId = 1,
                            WeightKg = 1300.0,
                            Year = 2004
                        },
                        new
                        {
                            Id = 2,
                            Horsepower = 180,
                            Make = "Toyota",
                            Model = "Celica GT 1998.",
                            RegistrationNumber = "ZG5678BB",
                            SuspensionId = 2,
                            TireId = 2,
                            WeightKg = 1200.0,
                            Year = 1998
                        },
                        new
                        {
                            Id = 3,
                            Horsepower = 140,
                            Make = "Toyota",
                            Model = "MR2 Spyder 2000.",
                            RegistrationNumber = "ZG9012CC",
                            SuspensionId = 3,
                            TireId = 3,
                            WeightKg = 1100.0,
                            Year = 2000
                        },
                        new
                        {
                            Id = 4,
                            Horsepower = 160,
                            Make = "Honda",
                            Model = "Civic EG6 1993.",
                            RegistrationNumber = "ZG3456DD",
                            SuspensionId = 4,
                            TireId = 4,
                            WeightKg = 1050.0,
                            Year = 1993
                        },
                        new
                        {
                            Id = 5,
                            Horsepower = 240,
                            Make = "Honda",
                            Model = "S2000 2001.",
                            RegistrationNumber = "ZG7890EE",
                            SuspensionId = 5,
                            TireId = 5,
                            WeightKg = 1250.0,
                            Year = 2001
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Email = "denis@mail.com",
                            Name = "Denis Horvat",
                            TeamId = 2,
                            Username = "denis_rx",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Name = "Takumi Fujiwara",
                            TeamId = 2,
                            Username = "takumi86",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Name = "Keisuke Takahashi",
                            TeamId = 3,
                            Username = "keisuke_fd",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            Name = "Ryosuke Takahashi",
                            TeamId = 3,
                            Username = "ryosuke_fc",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 5,
                            Age = 26,
                            Name = "Hiro Tanaka",
                            TeamId = 1,
                            Username = "hiro_s2k",
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Rim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SizeInJ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Rial",
                            Material = "Alloy",
                            Model = "Astorga",
                            SizeInJ = 8.0
                        },
                        new
                        {
                            Id = 2,
                            Make = "Japan Racing",
                            Material = "Alloy",
                            Model = "SL-03",
                            SizeInJ = 8.0
                        },
                        new
                        {
                            Id = 3,
                            Make = "Enkei",
                            Material = "Alloy",
                            Model = "RPF1",
                            SizeInJ = 7.5
                        },
                        new
                        {
                            Id = 4,
                            Make = "OZ Racing",
                            Material = "Alloy",
                            Model = "Ultraleggera",
                            SizeInJ = 7.0
                        },
                        new
                        {
                            Id = 5,
                            Make = "Volk Racing",
                            Material = "Forged Alloy",
                            Model = "TE37",
                            SizeInJ = 8.5
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BestTime")
                        .HasColumnType("time");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("Track")
                        .HasColumnType("int");

                    b.Property<int>("Weather")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.ToTable("Runs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestTime = new TimeSpan(0, 0, 5, 20, 0),
                            CarId = 1,
                            Date = new DateTime(2026, 5, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = 0,
                            DriverId = 1,
                            Track = 1,
                            Weather = 1
                        },
                        new
                        {
                            Id = 2,
                            BestTime = new TimeSpan(0, 0, 5, 0, 0),
                            CarId = 4,
                            Date = new DateTime(2026, 5, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = 1,
                            DriverId = 1,
                            Track = 0,
                            Weather = 1
                        },
                        new
                        {
                            Id = 3,
                            BestTime = new TimeSpan(0, 0, 5, 40, 0),
                            CarId = 2,
                            Date = new DateTime(2026, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = 0,
                            DriverId = 2,
                            Track = 2,
                            Weather = 2
                        },
                        new
                        {
                            Id = 4,
                            BestTime = new TimeSpan(0, 0, 5, 10, 0),
                            CarId = 3,
                            Date = new DateTime(2026, 5, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = 1,
                            DriverId = 3,
                            Track = 3,
                            Weather = 0
                        },
                        new
                        {
                            Id = 5,
                            BestTime = new TimeSpan(0, 0, 4, 55, 0),
                            CarId = 5,
                            Date = new DateTime(2026, 4, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = 0,
                            DriverId = 4,
                            Track = 1,
                            Weather = 0
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.RunFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunFiles");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.RunNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 5, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "Stock RX-8 setup, stable through medium-speed corners.",
                            RunId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 5, 4, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Note = "Civic with MTS Technik feels sharper on turn-in.",
                            RunId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 5, 4, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Note = "Celica on stock suspension struggled a bit in wet conditions.",
                            RunId = 3
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Suspension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FrontStiffness")
                        .HasColumnType("float");

                    b.Property<bool>("HasFrontStrutBar")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRearStrutBar")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeightAdjustable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStiffnessAdjustable")
                        .HasColumnType("bit");

                    b.Property<double?>("RearStiffness")
                        .HasColumnType("float");

                    b.Property<double>("RideHeightMm")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suspensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Mazda OEM",
                            HasFrontStrutBar = false,
                            HasRearStrutBar = false,
                            IsHeightAdjustable = false,
                            IsStiffnessAdjustable = false,
                            RideHeightMm = 120.0,
                            Type = "Stock"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota OEM",
                            HasFrontStrutBar = false,
                            HasRearStrutBar = false,
                            IsHeightAdjustable = false,
                            IsStiffnessAdjustable = false,
                            RideHeightMm = 120.0,
                            Type = "Stock"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "KW",
                            FrontStiffness = 9.0,
                            HasFrontStrutBar = true,
                            HasRearStrutBar = true,
                            IsHeightAdjustable = true,
                            IsStiffnessAdjustable = true,
                            RearStiffness = 8.0,
                            RideHeightMm = 85.0,
                            Type = "Coilover"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "MTS Technik",
                            FrontStiffness = 8.0,
                            HasFrontStrutBar = true,
                            HasRearStrutBar = true,
                            IsHeightAdjustable = true,
                            IsStiffnessAdjustable = true,
                            RearStiffness = 7.0,
                            RideHeightMm = 95.0,
                            Type = "Coilover"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Ohlins",
                            FrontStiffness = 9.5,
                            HasFrontStrutBar = true,
                            HasRearStrutBar = true,
                            IsHeightAdjustable = true,
                            IsStiffnessAdjustable = true,
                            RearStiffness = 8.5,
                            RideHeightMm = 88.0,
                            Type = "Coilover"
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sponsor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            Name = "Red Suns",
                            Sponsor = "HKS"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Croatia",
                            Name = "Sljeme Speed Stars"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Japan",
                            Name = "Night Kids",
                            Sponsor = "RE Amemiya"
                        });
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Tire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RimId")
                        .HasColumnType("int");

                    b.Property<double>("SizeInMm")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RimId");

                    b.ToTable("Tires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Pirelli",
                            Dot = "2024",
                            Model = "P Zero 225/45 R18",
                            RimId = 1,
                            SizeInMm = 225.0,
                            Type = "Street Performance"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Pirelli",
                            Dot = "2026",
                            Model = "P Zero 225/45 R17",
                            RimId = 2,
                            SizeInMm = 225.0,
                            Type = "Street Performance"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Bridgestone",
                            Dot = "2023",
                            Model = "RE71R 215/45 R17",
                            RimId = 3,
                            SizeInMm = 215.0,
                            Type = "Semi-Slick"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Toyo",
                            Dot = "2022",
                            Model = "R888R 225/45 R15",
                            RimId = 4,
                            SizeInMm = 225.0,
                            Type = "Semi-Slick"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Dunlop",
                            Dot = "2023",
                            Model = "Direzza 215/45 R17",
                            RimId = 5,
                            SizeInMm = 215.0,
                            Type = "Semi-Slick"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SljemeTimeAttack.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.AppUser", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Driver", "LinkedDriver")
                        .WithMany()
                        .HasForeignKey("LinkedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedDriver");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Car", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Driver", "Driver")
                        .WithMany("CarsOwned")
                        .HasForeignKey("DriverId");

                    b.HasOne("SljemeTimeAttack.Models.Suspension", "Suspension")
                        .WithMany()
                        .HasForeignKey("SuspensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SljemeTimeAttack.Models.Tire", "WheelSetup")
                        .WithMany()
                        .HasForeignKey("TireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Suspension");

                    b.Navigation("WheelSetup");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Driver", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Run", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SljemeTimeAttack.Models.Driver", "Driver")
                        .WithMany("Runs")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.RunFile", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Run", "Run")
                        .WithMany("Files")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.RunNote", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Run", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Tire", b =>
                {
                    b.HasOne("SljemeTimeAttack.Models.Rim", "Rim")
                        .WithMany()
                        .HasForeignKey("RimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rim");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Driver", b =>
                {
                    b.Navigation("CarsOwned");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Run", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SljemeTimeAttack.Models.Team", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
